### ISSUE TITLE
Compilation fails with gcc/g++ 5.3.1 (ubuntu 16.04)

### ISSUE THREAD

**Issue by mrwangxc** [PrismTech/opensplice#33] opened 2017-06-08 02:57 UTC
Trying to compile the openslice 6.7.170523OSS using a gcc 5.3.1 (default compiler in Ubuntu 16.04) ends up failing with the following message:
make[5]: Entering directory '/home/worker/project/VortexOpenSplice/src/tools/idlpp/bld/x86_64.linux-release'
gcc  -static-libgcc -L/home/worker/project/VortexOpenSplice/lib/x86_64.linux-release -std=c99 -D_GNU_SOURCE -DOSPL_LINUX -O3 -fno-strict-aliasing -flto -DNDEBUG -Wall -W -Wno-long-long -Wno-variadic-macros -Werror=uninitialized -D_POSIX_PTHREAD_SEMANTICS -D_REENTRANT -DDO_HOST_BY_NAME -Wconversion  idl_base.o idl_genLiteHelper.o idl_genCxxStreamsImpl.o idl_walk.o idl_registerType.o idl_genLiteISOCxxCopyin.o idl_catsDef.o idl_streamsDef.o idl_genC99Helper.o idl_genSacMeta.o idl_tmplExp.o idl_genCorbaCxxCopyin.o idl_genSajMeta.o idl_genSajType.o idl_genSajHolder.o idl_parser.o idl_genMetaHelper.o idl_genSACSSplDcps.o idl_genISOCxx2Copyout.o idl_genSACSType.o idl_map.o idl_typeSpecifier.o idl_genSACPPType.o idl_genSacTypedClassDefs.o idl_genC99Copyout.o idl_genSplHelper.o idl_genCxxStreamsDefs.o idl_genTypeSize.o idl_genJavaHelper.o idl_genCxxTypedClassImpl.o idl_genIdlHelper.o idl_fileMap.o idl_genISOCxxHeader.o idl_genSacType.o idl_genSACSHelper.o idl_genCxxStreamsIdl.o idl_stacDef.o idl_genSpliceType.o idl_genFaceISOCxx2Tmpl.o idl_scope.o idl_sematicRules.o idl_genISOCxx2Helper.o idl_genSACPPTypeImpl.o idl_genC99Tmpl.o idl_genCorbaCCopyout.o idl_genIdl.o idl_genISOCxx2Header.o idl_dependencies.o idl_genCorbaCHelper.o idl_genLiteCxxCopyout.o idl_genCorbaCCopyin.o idl_main.o idl_genC99Type.o idl_genCorbaJavaHelper.o idl_genCorbaCxxStreamsCcpp.o idl_genCxxTypedClassDefs.o idl_genLiteCxxCopyin.o idl_genCorbaCxxHelper.o idl_genSpliceLoad.o idl_databaseValidation.o idl_keyDef.o idl_dll.o idl_constSpecifier.o idl_genSpliceLiteType.o idl_genSacObjectControl.o idl_genISOCxx2Type.o idl_genCHelper.o idl_genSACPPTypedClassDefs.o idl_genSACSTypedClassDefs.o idl_genLiteISOCxxCopyout.o idl_unsupported.o idl_genTypeDescriptors.o idl_genCxxHelper.o idl_genCorbaCxxCcpp.o idl_genSACPPTypedClassImpl.o idl_genCorbaCxxCopyout.o idl_genSacHelper.o idl_genLanguageHelper.o idl_genSacTypedClassImpl.o idl_genSajTypedClass.o idl_genSpliceDep.o idl_genFaceJava.o -lc -lm -ldl -lpthread -lrt -lddscpp -lddshts  -o idlpp
/tmp/ccLuKydl.ltrans0.ltrans.o：In function ‘idl_base_yyparse’：
<artificial>:(.text+0xcfd4)：undefined reference to ‘preprocess_getc’
/tmp/ccLuKydl.ltrans2.ltrans.o：In function ‘idl_parseFile’：
<artificial>:(.text+0x523c)：undefined reference to ‘preprocess’
/tmp/ccLuKydl.ltrans6.ltrans.o：In function ‘main’：
<artificial>:(.text.startup+0x2c)：undefined reference to ‘init_preprocess’
<artificial>:(.text.startup+0x582)：undefined reference to ‘Ifile’
<artificial>:(.text.startup+0xe92)：undefined reference to ‘Ifile’
<artificial>:(.text.startup+0x15d0)：undefined reference to ‘init_preprocess’
<artificial>:(.text.startup+0x1619)：undefined reference to ‘Ifile’
/tmp/ccLuKydl.ltrans26.ltrans.o：In function ‘addDefine.lto_priv.705’：
<artificial>:(.text+0xa05)：undefined reference to ‘define’
collect2: error: ld returned 1 exit status
/home/worker/project/VortexOpenSplice/setup/makefiles/target-only.mak:110: recipe for target 'idlpp' failed
make[5]: *** [idlpp] Error 1
make[5]: Leaving directory '/home/worker/project/VortexOpenSplice/src/tools/idlpp/bld/x86_64.linux-release'
makefile:7: recipe for target 'all' failed

seems a link path problem. the tricks for gcc/g++ 4.9 (ubuntu 15.04) doesn't work here !

**Comment by kortstee** [comment] 2017-06-08 09:00
This seems a duplicate of https://github.com/PrismTech/opensplice/issues/30

**Comment by krepver** [comment] 2017-06-08 09:34
I have the same issue. Though, debug version compiles successfully.

**Comment by hansvanthag** [comment] 2017-06-08 09:43
please check this: http://forums.opensplice.org/index.php?/topic/2830-compilation-fails-with-gccg-531-ubuntu-1604/#entry5043

We'll update the instructions on our website accordingly .. sorry for the inconvenience

**Comment by michielb-prismtech** [comment] 2017-06-14 12:51
Issue is now fixed in build system, gcc/g++ tricks no longer required.

**Closed** 2017-06-14 12:51 UTC
Labels: bug
